### ISSUE TITLE
QETrackItem end, start type is Time

### ISSUE THREAD

**Issue by ckdwns9121** [aenhancers/types-for-adobe-extras#3]
![image](https://github.com/aenhancers/types-for-adobe-extras/assets/40492343/65c48116-7494-4b8e-8577-7b4ea1d47ecf)

![image](https://github.com/aenhancers/types-for-adobe-extras/assets/40492343/09aa200c-dd2f-4397-a427-fbdf26f3ac04)

**Comment by Klustre** [comment]
Can you explain what the problem is? Both are a [Time object](https://github.com/aenhancers/types-for-adobe-extras/blob/master/Premiere/12.0/qeDom.d.ts#L558-L563).

**Comment by justintaylor-dev** [comment]
@ckdwns9121 technically it's a QETime object which is different than a regular Time object. I've made the correction in 03f51276e87ab65f97a53ad11f25dfffe989ef09, thanks for pointing this out. 

Also FYI, the docsforadobe.dev you screenshotted refers to the standard API not the QE Dom API, so that is different.
